import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastNotification } from "@/src/components/UI/ToastNotification";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 dark:bg-[#191919]/95`}>{children}
        <ToastNotification  />
      </body>
    </html>
  );
}
